### ISSUE TITLE
Quick Question, where is the poolSize set?

### ISSUE THREAD

**Issue by PrimeLens** [mjhea0/node-postgres-todo#6]
Quick Question.  After reading brianc's comment about poolSize ([link](http://stackoverflow.com/questions/8484404/what-is-the-proper-way-to-use-the-node-js-postgresql-module/19282657#19282657)) just wondering where is the poolSize set?   
Edit:   btw great work. on this and the follow up repos that use sequelize and pgp

**Comment by mjhea0** [comment]
Check out the note -> https://github.com/brianc/node-postgres/wiki/Client#constructors

**Comment by mjhea0** [comment]
Cheers!

**Comment by PrimeLens** [comment]
Ok thanks,  I'll take a look at pg-pool
